// 茶叶术语词典数据
var GLOSSARY_DATA = [
  {term:'杀青', zh:'高温破坏酶活性，固定茶叶品质', en:'Enzyme Inactivation (Shaqing)', cat:'processing'},
  {term:'揉捻', zh:'塑造茶叶外形，挤出茶汁', en:'Rolling (Rounian)', cat:'processing'},
  {term:'发酵', zh:'茶叶氧化过程，形成特色品质', en:'Fermentation (Fajiao)', cat:'processing'},
  {term:'萎凋', zh:'鲜叶摊放失去部分水分', en:'Withering (Weitiao)', cat:'processing'},
  {term:'干燥', zh:'去除水分，固定茶叶品质', en:'Drying (Ganzao)', cat:'processing'},
  {term:'闷黄', zh:'黄茶特有的闷堆工艺', en:'Yellowing (Menhuang)', cat:'processing'},
  {term:'做青', zh:'乌龙茶摇青工艺，形成香气', en:'Tumbling (Zuoqing)', cat:'processing'},
  {term:'烘青', zh:'用烘干方式干燥茶叶', en:'Baked Drying (Hongqing)', cat:'processing'},
  {term:'蒸青', zh:'用蒸汽杀青，保留绿色', en:'Steamed Drying (Zhengqing)', cat:'processing'},
  {term:'炒青', zh:'用锅炒方式干燥', en:'Pan-fried Drying (Chaoqing)', cat:'processing'},
  {term:'回甘', zh:'入口微苦，后转为甘甜', en:'Sweet Aftertaste (Huigan)', cat:'quality'},
  {term:'挂杯香', zh:'茶香留于杯壁', en:'Aroma Lingering (Guabeixiang)', cat:'quality'},
  {term:'茶气', zh:'茶汤饮后身体的能量感', en:'Tea Energy (Chaqi)', cat:'quality'},
  {term:'喉韵', zh:'茶汤入喉后的韵味', en:'Throat Rhyme (Houyun)', cat:'quality'},
  {term:'锁喉', zh:'茶汤使喉部干燥不适', en:'Throat Tightening (Suohou)', cat:'quality'},
  {term:'收敛性', zh:'茶汤的收敛感', en:'Astringency (Liansuanxing)', cat:'quality'},
  {term:'耐泡度', zh:'茶叶可冲泡次数', en:'Brewing Durability (Naipao)', cat:'quality'},
  {term:'山场味', zh:'茶叶产地的特殊风味', en:'Terroir Character (Shanchang)', cat:'quality'},
  {term:'韵味', zh:'茶汤的整体韵味', en:'Overall Rhyme (Yunwei)', cat:'quality'},
  {term:'花果香', zh:'花香和果香的复合香气', en:'Floral & Fruity (Huaguoxiang)', cat:'quality'},
  {term:'板栗香', zh:'类似板栗的熟香', en:'Chestnut Aroma (Banlixiang)', cat:'quality'},
  {term:'炒豆香', zh:'炒制过程中的香气', en:'Roasted Bean Aroma (Chaodou)', cat:'quality'},
  {term:'毫香', zh:'细嫩茶叶的特有香气', en:'Fine Hair Aroma (Haoxiang)', cat:'quality'},
  {term:'兰香', zh:'兰花的优雅香气', en:'Orchid Aroma (Lanxiang)', cat:'quality'},
  {term:'蜜香', zh:'蜂蜜般的甘甜香气', en:'Honey Aroma (Mixiang)', cat:'quality'},
  {term:'枣香', zh:'红枣的甜香', en:'Jujube Aroma (Zaoxiang)', cat:'quality'},
  {term:'陈香', zh:'陈年茶叶的特殊香气', en:'Aged Aroma (Chenxiang)', cat:'quality'},
  {term:'药香', zh:'类似中药的香气', en:'Medicinal Aroma (Yaoxiang)', cat:'quality'},
  {term:'苦涩', zh:'茶汤的苦味和涩味', en:'Bitter & Astringent (Kuku)', cat:'quality'},
  {term:'醇厚', zh:'茶汤浓稠饱满', en:'Rich & Thick (Chunhou)', cat:'quality'},
  {term:'鲜爽', zh:'新鲜爽口的感觉', en:'Fresh & Crisp (Xianshuang)', cat:'quality'},
  {term:'六大茶类', zh:'绿茶/白茶/黄茶/青茶/红茶/黑茶', en:'Six Tea Categories', cat:'teatype'},
  {term:'普洱', zh:'云南特产，后发酵茶', en:"Pu'er Tea", cat:'teatype'},
  {term:'乌龙', zh:'半发酵茶，亦称青茶', en:'Oolong Tea', cat:'teatype'},
  {term:'铁观音', zh:'闽南乌龙代表品种', en:'Tieguanyin', cat:'teatype'},
  {term:'单丛', zh:'广东乌龙，香气高锐', en:'Dancong Oolong', cat:'teatype'},
];
