[
  {
    id: 195,
    name: '千家寨',
    type: '普洱',
    origin: '云南镇沅',
    grade: '特级',
    period: '唐代',
    desc: '千年古茶，野生茶王',
    detail: '产于云南镇沅县哀牢山千家寨，海拔2100米以上，有千年野生古茶树群落。',
    story: '千家寨野生古茶树群落是目前发现的面积最大、最原始的野生茶树群落。',
    efficacy: '降脂减肥、清热解毒、抗氧化',
    gradeDesc: '特级：条索肥壮，色泽墨绿，白毫显露',
    color: '橙黄透亮',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶', steps: '洗茶后快出汤'},
    storage: '通风干燥自然存放',
    foodPairing: '云南菜、重口味菜',
    tastingTerms: '野韵十足回甘持久',
    suitableCrowd: '普洱发烧友、中年男性',
    flavorProfile: {bitter: 6, astringent: 7, sweet: 6, fragrant: 7, returning: 9},
    suitableSeason: '四季皆宜',
    originDetail: '云南省普洱市镇沅彝族哈尼族拉祜族自治县哀牢山千家寨，海拔2000-2500米',
    storyExtended: '千家寨位于哀牢山国家级自然保护区腹地，是世界上最大的野生茶树群落所在地。其中最古老的野生茶树树龄达2700余年，被称为\"野生茶树王\"。这里的茶叶因长期处于野生状态，茶气霸道，野韵十足。',
    teaEmoji: '🌲',
    category: '生普',
    wuXing: '木',
    efficacyDetail: '千家寨古树茶含有丰富的茶多酚和儿茶素，具有显著的降脂减肥、清热解毒、抗氧化功效。野生茶的原始成分使其保健价值更高。',
    altitude: '海拔2100-2500米',
    priceRange: 4,
    suitableTime: '早',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 5
  },
  {
    id: 196,
    name: '景迈山古树',
    type: '普洱',
    origin: '云南澜沧',
    grade: '特级',
    period: '唐代',
    desc: '景迈古茶，万亩茶林',
    detail: '产于云南澜沧景迈山，有全世界保存最完整、面积最大的人工栽培型古茶园。',
    story: '景迈山古茶林入选世界农业遗产。',
    efficacy: '降脂减肥、抗氧化、防癌抗癌',
    gradeDesc: '特级：条索紧结，色泽墨绿，白毫显露',
    color: '金黄透亮',
    brewing: {temperature: '95℃', teaware: '紫砂壶', steps: '洗茶后快出汤'},
    storage: '通风干燥自然存放',
    foodPairing: '傣族菜、云南菜',
    tastingTerms: '兰香馥郁甜润回甘',
    suitableCrowd: '女性、普洱爱好者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 9, fragrant: 10, returning: 8},
    suitableSeason: '四季皆宜',
    originDetail: '云南省普洱市澜沧拉祜族自治县景迈山，海拔1100-1700米',
    storyExtended: '景迈山古茶林是世界上保存最完整、面积最大的人工栽培型古茶园。茶林总面积达2.8万亩，其中最古老的茶树已有1400多年历史。这里保存着完整的茶树演化链条，是研究茶树起源的重要基地。',
    teaEmoji: '🍃',
    category: '生普',
    wuXing: '木',
    efficacyDetail: '景迈茶以高扬的花香和甜润的滋味著称，含有丰富的芳香物质和茶多酚，具有降脂减肥、抗氧化、防癌抗癌的功效。',
    altitude: '海拔1100-1700米',
    priceRange: 4,
    suitableTime: '早+午',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '世界农业遗产',
    rating: 5
  },
  {
    id: 197,
    name: '邦崴',
    type: '普洱',
    origin: '云南澜沧',
    grade: '特级',
    period: '清代',
    desc: '邦崴古茶，过渡型茶王',
    detail: '产于云南澜沧邦崴乡，以过渡型古茶树著称，是茶树演化史上的活化石。',
    story: '邦崴古茶树是世界上第一棵发现论证茶树起源的过渡型古茶树。',
    efficacy: '降脂减肥、消食化积、提神醒脑',
    gradeDesc: '特级：条索肥壮，色泽墨绿',
    color: '橙黄明亮',
    brewing: {temperature: '95℃', teaware: '紫砂壶', steps: '功夫泡'},
    storage: '通风干燥',
    foodPairing: '云南菜',
    tastingTerms: '醇厚甘甜',
    suitableCrowd: '普洱收藏者、中年人',
    flavorProfile: {bitter: 4, astringent: 5, sweet: 8, fragrant: 7, returning: 9},
    suitableSeason: '四季皆宜',
    originDetail: '云南省普洱市澜沧拉祜族自治县富邦乡邦崴村，海拔1500-1900米',
    storyExtended: '邦崴古茶树是一棵有着1000多年历史的过渡型古茶树，1991年被发现。这棵茶树同时具有野生茶树和栽培茶树的特征，是茶树从野生向栽培演化的活证据，在茶树起源研究中具有重要地位。',
    teaEmoji: '🏔️',
    category: '生普',
    wuXing: '土',
    efficacyDetail: '邦崴茶具有降脂减肥、消食化积、提神醒脑的功效，是普洱茶中的珍稀品种。',
    altitude: '海拔1500-1900米',
    priceRange: 4,
    suitableTime: '早',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '过渡型茶王',
    rating: 5
  },
  {
    id: 198,
    name: '邦苯',
    type: '普洱',
    origin: '云南易武',
    grade: '特级',
    period: '清代',
    desc: '易武邦苯，柔中美韵',
    detail: '产于云南易武茶区邦苯村，是易武茶区的新秀。',
    story: '邦苯茶近年来在普洱茶市场上备受关注。',
    efficacy: '降脂减肥、养胃护胃',
    gradeDesc: '特级：条索肥壮，白毫显露',
    color: '橙黄透亮',
    brewing: {temperature: '95℃', teaware: '紫砂壶', steps: '洗茶后慢出汤'},
    storage: '通风干燥自然存放',
    foodPairing: '云南菜、清淡菜',
    tastingTerms: '柔甜细腻回味悠长',
    suitableCrowd: '女性、普洱入门者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 9, fragrant: 7, returning: 9},
    suitableSeason: '四季皆宜',
    originDetail: '云南省西双版纳傣族自治州勐腊县易武乡邦苯村，海拔1200-1500米',
    storyExtended: '邦苯村位于易武茶区的腹地，生态环境优越，古茶树资源丰富。近年来随着古树茶概念的兴起，邦苯茶以其柔甜的口感逐渐受到茶友追捧。',
    teaEmoji: '🍂',
    category: '生普',
    wuXing: '土',
    efficacyDetail: '邦苯茶继承了易武茶的柔甜特点，对胃刺激小，具有降脂减肥、养胃护胃的功效。',
    altitude: '海拔1200-1500米',
    priceRange: 3,
    suitableTime: '早',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 4
  },
  {
    id: 199,
    name: '那卡',
    type: '普洱',
    origin: '云南勐海',
    grade: '特级',
    period: '清代',
    desc: '勐海那卡，小叶种精品',
    detail: '产于云南勐海县布朗山那卡村，是布朗山茶区的精品。',
    story: '那卡茶在清代是土司专供茶。',
    efficacy: '降脂减肥、消食去腻',
    gradeDesc: '特级：条索紧结，色泽墨绿',
    color: '橙黄明亮',
    brewing: {temperature: '95℃', teaware: '紫砂壶', steps: '功夫泡'},
    storage: '通风干燥',
    foodPairing: '云南菜、重口味菜',
    tastingTerms: '苦涩化甘茶气足',
    suitableCrowd: '男性、普洱老茶客',
    flavorProfile: {bitter: 5, astringent: 6, sweet: 7, fragrant: 7, returning: 9},
    suitableSeason: '四季皆宜',
    originDetail: '云南省西双版纳傣族自治州勐海县布朗山乡那卡村，海拔1600-1800米',
    storyExtended: '那卡是布朗山茶区中最具代表性的村寨之一，清代时是布朗族土司的专属茶园。那卡茶茶气足、苦涩味重，但回甘极好，有\"小班章\"之称。',
    teaEmoji: '🍂',
    category: '生普',
    wuXing: '土',
    efficacyDetail: '那卡茶茶气足，具有显著的降脂减肥、消食去腻功效，适合重口味饮食者饮用。',
    altitude: '海拔1600-1800米',
    priceRange: 3,
    suitableTime: '早',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '小班章',
    rating: 4
  },
  {
    id: 200,
    name: '广别',
    type: '普洱',
    origin: '云南勐海',
    grade: '特级',
    period: '明代',
    desc: '布朗广别，妖茶传说',
    detail: '产于云南勐海县布朗山广别寨，以独特的口感著称。',
    story: '广别茶被称为\"妖茶\"，因其口感变化丰富。',
    efficacy: '降脂减肥、清热解毒',
    gradeDesc: '特级：条索肥壮，白毫显露',
    color: '金黄透亮',
    brewing: {temperature: '95℃', teaware: '紫砂壶', steps: '洗茶后快出汤'},
    storage: '通风干燥',
    foodPairing: '云南菜',
    tastingTerms: '口感独特变化丰富',
    suitableCrowd: '普洱发烧友、收藏者',
    flavorProfile: {bitter: 4, astringent: 5, sweet: 8, fragrant: 8, returning: 9},
    suitableSeason: '四季皆宜',
    originDetail: '云南省西双版纳傣族自治州勐海县布朗山乡广别寨，海拔1500-1700米',
    storyExtended: '广别茶被称为\"妖茶\"，是因为其口感变化丰富，第一泡与第十泡的滋味截然不同，令人称奇。这种独特的口感变化源于广别古茶树生长环境的特殊性和茶叶内含物质的丰富性。',
    teaEmoji: '🍂',
    category: '生普',
    wuXing: '木',
    efficacyDetail: '广别茶口感独特，具有降脂减肥、清热解毒的功效，是普洱茶中的珍稀品种。',
    altitude: '海拔1500-1700米',
    priceRange: 4,
    suitableTime: '早',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '妖茶',
    rating: 5
  },
  {
    id: 201,
    name: '莽枝',
    type: '普洱',
    origin: '云南勐腊',
    grade: '特级',
    period: '清代',
    desc: '古六大茶山，莽枝古茶',
    detail: '产于云南勐腊县莽枝山，是古六大茶山之一。',
    story: '莽枝山是古六大茶山之一，历史悠久。',
    efficacy: '降脂减肥、消食化积',
    gradeDesc: '特级：条索紧结，色泽墨绿',
    color: '橙黄透亮',
    brewing: {temperature: '95℃', teaware: '紫砂壶', steps: '功夫泡'},
    storage: '通风干燥',
    foodPairing: '云南菜',
    tastingTerms: '醇厚回甘',
    suitableCrowd: '中年人、普洱收藏者',
    flavorProfile: {bitter: 4, astringent: 5, sweet: 7, fragrant: 7, returning: 8},
    suitableSeason: '四季皆宜',
    originDetail: '云南省西双版纳傣族自治州勐腊县象明乡莽枝山，海拔1100-1500米',
    storyExtended: '莽枝山是古六大茶山之一，历史可追溯到清代。这里曾是茶马古道的重要节点，茶叶贸易繁荣一时。莽枝茶以其醇厚的口感和持久的回甘而著称。',
    teaEmoji: '🍂',
    category: '生普',
    wuXing: '土',
    efficacyDetail: '莽枝茶具有降脂减肥、消食化积、提神醒脑的功效，是古六大茶山的代表性品种。',
    altitude: '海拔1100-1500米',
    priceRange: 3,
    suitableTime: '早',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '古六大茶山',
    rating: 4
  },
  {
    id: 202,
    name: '革登',
    type: '普洱',
    origin: '云南勐腊',
    grade: '特级',
    period: '清代',
    desc: '古六大茶山，革登贡茶',
    detail: '产于云南勐腊县革登山，是古六大茶山之一，曾为清代贡茶。',
    story: '革登茶在清代是皇室贡品，有\"革登贡茶甲天下\"之誉。',
    efficacy: '降脂减肥、养胃护胃',
    gradeDesc: '特级：条索肥壮，色泽墨绿',
    color: '橙黄明亮',
    brewing: {temperature: '90-95℃', teaware: '紫砂壶', steps: '轻柔冲泡'},
    storage: '通风干燥',
    foodPairing: '清淡菜、云南菜',
    tastingTerms: '细腻甘甜回味悠长',
    suitableCrowd: '女性、胃寒者、普洱爱好者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 9, fragrant: 7, returning: 9},
    suitableSeason: '四季皆宜',
    originDetail: '云南省西双版纳傣族自治州勐腊县象明乡革登山，海拔1200-1600米',
    storyExtended: '革登山是古六大茶山之一，海拔最高的一座。清代时，革登茶作为皇室贡品，产量极少，品质卓越。革登茶口感细腻甜润，是普洱茶中\"甜茶\"的代表之一。',
    teaEmoji: '🍂',
    category: '生普',
    wuXing: '土',
    efficacyDetail: '革登茶以细腻甜润著称，对胃刺激极小，具有降脂减肥、养胃护胃的功效，适合胃寒者和女性饮用。',
    altitude: '海拔1200-1600米',
    priceRange: 4,
    suitableTime: '早+午',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '贡茶',
    rating: 5
  }

]