[{
    id: 184,
    name: '六堡茶·特级',
    type: '黑茶',
    origin: '广西梧州',
    grade: '特级',
    period: '清代',
    desc: '槟榔香醇，陈年韵味',
    detail: '特级六堡茶产于广西梧州六堡镇，选用百年老茶树原料，经传统工艺精制而成。茶叶品质卓越，槟榔香更加浓郁纯正。',
    story: '暂无记载',
    efficacy: '祛湿热、解毒消暑、消食化滞、降血压',
    gradeDesc: '特级：条索肥壮，色泽褐红油润，槟榔香浓郁持久',
    color: '红浓透亮，槟榔香显',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶', steps: '洗茶后冲泡，第一泡10秒出汤，后续每泡延长，可冲泡20次以上'},
    storage: '通风干燥保存，避免潮湿和异味，可长期保存越陈越香',
    foodPairing: '粤菜、海鲜、广西特色菜、陈皮糖',
    tastingTerms: '槟榔香浓、汤色红浓、滋味醇厚、回甘绵长',
    suitableCrowd: '茶收藏家、南方潮湿地区居民、老年人、胃寒者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 6, fragrant: 8, returning: 9},
    suitableSeason: '秋季、冬季、春季',
    originDetail: '广西壮族自治区梧州市苍梧县六堡镇，海拔200-800米，百年老茶树林',
    storyExtended: '特级六堡茶是六堡茶中的上品，产于广西梧州六堡镇。这里气候温暖湿润，土壤偏酸性，非常适合茶树生长。百年老茶树的茶叶内含物质更加丰富，经过传统工艺精制后，槟榔香更加浓郁纯正，滋味更加醇厚甘甜。特级六堡茶具有很好的收藏价值，存放十年以上品质更佳，被茶界称为\"可以喝的古董\"。',
    teaEmoji: '🏝️',
    category: '广西黑茶',
    wuXing: '水',
    efficacyDetail: '特级六堡茶具有更强的祛湿热、解毒消暑、消食化滞功效。富含茶褐素和维生素，对调节肠胃功能、降血压、降血脂有显著效果。陈年六堡茶温润醇和，对胃刺激小，适合各类人群饮用。',
    altitude: '海拔300-800米',
    priceRange: 3,
    suitableTime: '午+晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 3,
    organic: false,
    award: '',
    rating: 5
  },
  {
    id: 185,
    name: '雅安藏茶·金尖',
    type: '黑茶',
    origin: '四川雅安',
    grade: '特级',
    period: '唐代',
    desc: '金尖藏茶，皇室贡品',
    detail: '雅安金尖藏茶产于四川省雅安市，是藏茶中的极品。历史上曾作为皇室贡品，品质卓越，口感醇厚。',
    story: '暂无记载',
    efficacy: '助消化、补充维生素、降脂减肥、抗氧化',
    gradeDesc: '特级：砖面平整，金尖显露，色泽褐红，汤色红浓透亮',
    color: '红浓透亮，滋味醇厚',
    brewing: {temperature: '95-100℃', teaware: '煮茶壶或紫砂壶', steps: '熬煮效果最佳，先洗茶后熬煮30秒出汤，可多次煮饮'},
    storage: '通风干燥保存，避免受潮，可长期保存',
    foodPairing: '酥油茶、糌粑、牛羊肉、奶酪',
    tastingTerms: '金尖显露、汤色红浓、滋味醇厚、高原茶香',
    suitableCrowd: '藏族同胞、高原居民、茶收藏家、注重养生者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 5, fragrant: 5, returning: 8},
    suitableSeason: '秋季、冬季',
    originDetail: '四川省雅安市蒙山、雅安雨城区，海拔800-1500米，川西高原',
    storyExtended: '雅安金尖藏茶是藏茶中的极品，产于四川省雅安市。雅安是四川著名的茶叶产区，气候温和，雨量充沛，土壤肥沃。金尖藏茶选用优质原料，制作工艺考究，品质卓越。历史上金尖藏茶曾作为皇室贡品，品质要求极高。其特点是砖面平整，金尖显露，汤色红浓，滋味醇厚，是藏茶爱好者的珍品。',
    teaEmoji: '🏔️',
    category: '边销黑茶',
    wuXing: '水',
    efficacyDetail: '雅安金尖藏茶富含维生素C、维生素B族和矿物质，具有助消化、补充维生素、降脂减肥、抗氧化的功效。金尖藏茶品质更优，保健效果更好，对调节肠胃功能、补充营养有显著作用。',
    altitude: '海拔800-1500米',
    priceRange: 2,
    suitableTime: '晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 3,
    organic: false,
    award: '',
    rating: 4.5
  },
  {
    id: 186,
    name: '老青茶·陈香',
    type: '黑茶',
    origin: '湖北咸宁',
    grade: '一级',
    period: '清代',
    desc: '老青陈香，越陈越醇',
    detail: '老青茶陈香款产于湖北咸宁，选用优质原料，经多年干仓存放转化，形成独特的陈香品质。',
    story: '暂无记载',
    efficacy: '降脂减肥、助消化、养胃护胃、抗衰老',
    gradeDesc: '一级：砖形完整，色泽青褐带红，汤色黄红，陈香明显',
    color: '黄红明亮，陈香浓郁',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶或煮茶壶', steps: '洗茶后冲泡或煮茶，每泡20-30秒出汤，陈香更佳'},
    storage: '通风干燥保存，干仓存放，避免受潮，可长期保存',
    foodPairing: '湖北菜、湘菜、火锅、油腻食品',
    tastingTerms: '陈香明显、汤色黄红、滋味醇和、回甘持久',
    suitableCrowd: '中老年人、收藏爱好者、肥胖者、以肉食为主者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 6, fragrant: 6, returning: 8},
    suitableSeason: '秋季、冬季',
    originDetail: '湖北省咸宁市赤壁市赵李桥镇，海拔100-500米，鄂南山区',
    storyExtended: '老青茶陈香款是湖北老青茶中的优质品种，产于咸宁市赤壁市。老青茶的传统销售区域是内蒙古、新疆等牧区，但随着茶文化的发展，老青茶也受到了越来越多茶友的喜爱。陈香款老青茶经过多年干仓存放，茶叶中的成分逐渐转化，形成了独特的陈香品质，口感更加醇和甘甜。',
    teaEmoji: '🐑',
    category: '湖北老青茶',
    wuXing: '水',
    efficacyDetail: '老青茶陈香款具有降脂减肥、助消化、养胃护胃、抗衰老的功效。经过多年存放转化，茶叶中的大分子物质被分解，更易于人体吸收，对调节血脂、软化血管有显著效果。',
    altitude: '海拔100-500米',
    priceRange: 2,
    suitableTime: '晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 4
  },
  {
    id: 187,
    name: '安化茯砖·金花',
    type: '黑茶',
    origin: '湖南安化',
    grade: '特级',
    period: '明代',
    desc: '金花茂盛，菌香独特',
    detail: '安化茯砖金花款产于湖南安化，选用云台山大叶种为原料，茯砖中金花茂盛，菌香独特，品质卓绝。',
    story: '暂无记载',
    efficacy: '助消化、降脂减肥、调节肠道菌群、增强免疫',
    gradeDesc: '特级：砖面平整，金花茂盛如星，色泽黑褐，汤色红浓',
    color: '红浓透亮，金花点点，菌香明显',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶或盖碗', steps: '洗茶后冲泡，第一泡15秒出汤，后续每泡延长，可煮饮'},
    storage: '通风干燥保存，避免潮湿，金花茯砖可长期保存且越陈越香',
    foodPairing: '湘菜、火锅、烤肉、油腻食品、重口味菜',
    tastingTerms: '金花茂盛、菌香明显、汤色红浓、滋味醇厚',
    suitableCrowd: '男性、中老年人、肥胖者、肠道不适者、免疫力低下者',
    flavorProfile: {bitter: 3, astringent: 4, sweet: 5, fragrant: 6, returning: 8},
    suitableSeason: '秋季、冬季',
    originDetail: '湖南省益阳市安化县冷市镇、小淹镇等地，海拔300-1200米，安化云台山大叶种',
    storyExtended: '安化茯砖金花款是安化黑茶中的珍品，产于湖南省安化县。安化是著名的茶叶产区，安化云台山大叶种是制作黑茶的优质原料。茯砖茶的最大特点是有金花，学名\"冠突散囊菌\"，是一种益生菌，在特定温湿度条件下在茶叶中生长繁殖。金花越多，茶的品质越好，保健功效也越显著。安化茯砖金花款金花茂盛，菌香独特，是茶中上品。',
    teaEmoji: '🧱',
    category: '湖南黑茶',
    wuXing: '水',
    efficacyDetail: '安化茯砖金花款具有助消化、降脂减肥、调节肠道菌群、增强免疫力的功效。金花（冠突散囊菌）是天然益生菌，对促进消化、分解脂肪、调节肠道菌群有显著效果。经常饮用可改善肠胃功能，提高免疫力。',
    altitude: '海拔300-1000米',
    priceRange: 3,
    suitableTime: '晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 3,
    organic: false,
    award: '',
    rating: 4.5
  },
  {
    id: 188,
    name: '普洱古树·生茶',
    type: '黑茶',
    origin: '云南西双版纳',
    grade: '特级',
    period: '唐代',
    desc: '千年古树，原始生态',
    detail: '普洱古树生茶产于云南西双版纳勐海县，选用千年古茶树原料，原始生态环境，茶叶内含物质极为丰富。',
    story: '暂无记载',
    efficacy: '降脂减肥、抗氧化、延缓衰老、防癌抗癌',
    gradeDesc: '特级：条索肥壮，色泽墨绿带褐，汤色金黄透亮，山野韵强',
    color: '金黄透亮，山野韵强',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶或盖碗', steps: '洗茶后冲泡，第一泡5秒出汤，后续每泡延长，可冲泡20次以上'},
    storage: '通风干燥保存，避免潮湿，可长期保存越陈越香',
    foodPairing: '云南菜、烤肉、火锅、海鲜',
    tastingTerms: '山野韵强、汤色金黄、滋味浓烈、回甘持久、越陈越香',
    suitableCrowd: '男性、茶收藏家、注重养生者、普洱茶爱好者',
    flavorProfile: {bitter: 5, astringent: 6, sweet: 5, fragrant: 7, returning: 9},
    suitableSeason: '秋季、冬季',
    originDetail: '云南省西双版纳傣族自治州勐海县巴达山、布朗山，海拔1500-2000米，古茶树林',
    storyExtended: '普洱古树生茶产于云南西双版纳勐海县的古茶树林，这里有许多千年古茶树。古茶树生长在原始森林中，与自然融为一体，不受现代污染。古茶树的根系深扎地下，吸收着深层土壤中的矿物质和微量元素，茶叶内含物质极为丰富。采摘古茶树的鲜叶制作普洱生茶，品质卓绝，口感浓烈，山野韵强，具有很好的收藏价值。存放多年后，茶叶转化更加完美，滋味更加醇和甘甜。',
    teaEmoji: '🌳',
    category: '云南普洱生茶',
    wuXing: '水',
    efficacyDetail: '普洱古树生茶具有降脂减肥、抗氧化、延缓衰老、防癌抗癌的功效。古树茶富含茶多酚、氨基酸、矿物质等成分，抗氧化能力更强，对清除自由基、延缓衰老、预防癌症有显著效果。长期饮用可调节血脂、血压，保护心血管健康。',
    altitude: '海拔1500-2000米',
    priceRange: 3,
    suitableTime: '午+晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 4,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 5
  },
  {
    id: 189,
    name: '青砖茶·米砖',
    type: '黑茶',
    origin: '湖北赤壁',
    grade: '一级',
    period: '清代',
    desc: '米砖紧实，图案精美',
    detail: '青砖茶米砖产于湖北赤壁赵李桥，是传统青砖茶中的精品。砖面压制精美图案，形似米砖，故名米砖。',
    story: '暂无记载',
    efficacy: '助消化、降脂减肥、利尿、解暑',
    gradeDesc: '一级：砖形似米，图案精美，色泽青褐，汤色黄红',
    color: '黄红明亮，滋味醇和',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶或煮茶壶', steps: '洗茶后冲泡或煮茶，每泡20-30秒出汤'},
    storage: '通风干燥保存，避免受潮，可长期保存',
    foodPairing: '湖北菜、湘菜、火锅、面食',
    tastingTerms: '米砖造型、图案精美、汤色黄红、滋味醇和',
    suitableCrowd: '男性、中老年人、肥胖者、收藏爱好者',
    flavorProfile: {bitter: 3, astringent: 4, sweet: 5, fragrant: 4, returning: 7},
    suitableSeason: '秋季、冬季',
    originDetail: '湖北省咸宁市赤壁市赵李桥镇，海拔100-500米，鄂南茶区',
    storyExtended: '青砖茶米砖是湖北赤壁的传统特产，因砖形似米、压制精美图案而得名\"米砖\"。米砖是青砖茶中的精品，造型独特，图案精美，既有实用价值又有观赏价值。赵李桥是青砖茶的核心产区，有着数百年的制茶历史。米砖选用优质原料，制作工艺考究，品质上乘，深受茶友和收藏家的喜爱。',
    teaEmoji: '🧱',
    category: '湖北黑茶',
    wuXing: '水',
    efficacyDetail: '青砖茶米砖具有助消化、降脂减肥、利尿解暑的功效。适合以肉食为主的人群和肥胖者饮用，对促进消化、降低血脂有良好效果。米砖造型精美，也是馈赠亲友的佳品。',
    altitude: '海拔100-500米',
    priceRange: 2,
    suitableTime: '晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 4
  },
  {
    id: 190,
    name: '云南熟砖·宫廷',
    type: '黑茶',
    origin: '云南昆明',
    grade: '特级',
    period: '现代',
    desc: '宫廷熟砖，嫩度高',
    detail: '云南宫廷熟砖产于云南省昆明市，选用细嫩茶芽为原料，经人工渥堆发酵制成。嫩度高，口感更加细腻顺滑。',
    story: '暂无记载',
    efficacy: '降脂减肥、助消化、养胃护胃、美容养颜',
    gradeDesc: '特级：砖形端正，色泽红褐，嫩芽显露，汤色红浓',
    color: '红浓透亮，细腻顺滑',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶', steps: '洗茶后冲泡，第一泡5秒出汤，后续每泡延长，可冲泡15次以上'},
    storage: '通风干燥保存，避免潮湿，可长期保存',
    foodPairing: '云南菜、粤菜、火锅、烤肉',
    tastingTerms: '宫廷嫩芽、汤色红浓、滋味醇厚、入口细腻',
    suitableCrowd: '女性、中老年人、养胃需求者、注重美容者',
    flavorProfile: {bitter: 1, astringent: 2, sweet: 7, fragrant: 5, returning: 9},
    suitableSeason: '秋季、冬季、春季',
    originDetail: '云南省昆明市、西双版纳等地，云南大叶种细嫩芽叶',
    storyExtended: '云南宫廷熟砖是普洱熟茶中的精品，产于云南省昆明市及西双版纳地区。\"宫廷\"指的是选用细嫩的茶芽为原料，嫩度高，茶叶中的氨基酸和芳香物质含量更丰富。宫廷熟砖的制作工艺与普通熟茶相同，但原料更优，因此口感更加细腻顺滑，汤色更加红浓透亮，适合对茶叶口感有较高要求的茶友。',
    teaEmoji: '🫖',
    category: '云南普洱熟茶',
    wuXing: '水',
    efficacyDetail: '云南宫廷熟砖具有降脂减肥、助消化、养胃护胃、美容养颜的功效。细嫩原料含有丰富的氨基酸和维生素，对滋养肌肤、延缓衰老有良好效果。口感细腻温润，对胃刺激小，适合各类人群饮用。',
    altitude: '海拔1200-1800米',
    priceRange: 2,
    suitableTime: '午+晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 3,
    organic: false,
    award: '',
    rating: 4.5
  },
  {
    id: 191,
    name: '泾阳茯茶·手筑',
    type: '黑茶',
    origin: '陕西泾阳',
    grade: '特级',
    period: '明代',
    desc: '手工筑制，金花饱满',
    detail: '泾阳手筑茯茶产于陕西泾阳，采用传统手工筑制工艺，金花更加饱满茂盛，品质优于机制茯茶。',
    story: '暂无记载',
    efficacy: '助消化、降脂减肥、调节肠道、降血压、增强免疫',
    gradeDesc: '特级：砖形端正，手筑纹理清晰，金花饱满茂盛，色泽褐红',
    color: '红浓透亮，金花饱满，菌香浓郁',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶或盖碗', steps: '洗茶后冲泡，每泡15-20秒出汤，可煮饮，煮饮口感更佳'},
    storage: '通风干燥保存，避免潮湿，手筑茯茶可长期保存越陈越香',
    foodPairing: '西北菜、面食、烤肉、火锅',
    tastingTerms: '手筑工艺、金花饱满、菌香浓郁、汤色红浓、滋味醇厚',
    suitableCrowd: '男性、中老年人、肥胖者、肠道不适者、免疫力低下者',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 6, fragrant: 7, returning: 8},
    suitableSeason: '秋季、冬季',
    originDetail: '陕西省咸阳市泾阳县，关中平原，海拔400-600米，渭河平原',
    storyExtended: '泾阳手筑茯茶是茯茶中的上品，产于陕西省咸阳市泾阳县。传统茯茶采用手工筑制工艺，将茶叶填入模具中人工压制成形。手筑茯茶密度适中，透气性好，金花更容易生长繁殖，因此金花更加饱满茂盛。手筑茯茶的制作工艺被列入非物质文化遗产，体现了中国传统制茶技艺的精髓。手筑茯茶口感更加醇厚，菌香更加浓郁，是茶中珍品。',
    teaEmoji: '🌾',
    category: '陕西茯茶',
    wuXing: '水',
    efficacyDetail: '泾阳手筑茯茶具有助消化、降脂减肥、调节肠道菌群、降血压、增强免疫力的功效。手筑工艺使金花更加饱满，保健效果更显著。长期饮用可改善肠胃功能，调节血脂，提高免疫力，对人体健康大有裨益。',
    altitude: '海拔400-600米',
    priceRange: 3,
    suitableTime: '晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 3,
    organic: false,
    award: '',
    rating: 4.5
  },
  {
    id: 192,
    name: '梧州六堡·老茶',
    type: '黑茶',
    origin: '广西梧州',
    grade: '特级',
    period: '清代',
    desc: '百年老茶，品质珍贵',
    detail: '梧州六堡老茶产于广西梧州六堡镇，选用百年树龄的老茶树原料，品质珍贵稀有，具有独特的陈香和药香。',
    story: '暂无记载',
    efficacy: '祛湿热、解毒消暑、消食化滞、降三高、抗衰老',
    gradeDesc: '特级：条索肥壮带梗，色泽褐红油润，陈香药香明显，汤色红浓',
    color: '红浓透亮，陈香药香浓郁',
    brewing: {temperature: '95-100℃', teaware: '紫砂壶', steps: '洗茶后冲泡或煮茶，第一泡10秒出汤，可冲泡20次以上'},
    storage: '通风干燥保存，避免潮湿，可长期保存，是收藏佳品',
    foodPairing: '粤菜、海鲜、广西菜、陈皮、参茸',
    tastingTerms: '老茶树龄、陈香药香、汤色红浓、滋味醇厚回甘',
    suitableCrowd: '茶收藏家、老年人、三高患者、南方潮湿地区居民',
    flavorProfile: {bitter: 2, astringent: 3, sweet: 7, fragrant: 9, returning: 9},
    suitableSeason: '秋季、冬季、春季',
    originDetail: '广西壮族自治区梧州市苍梧县六堡镇，海拔200-800米，百年老茶树林',
    storyExtended: '梧州六堡老茶是六堡茶中的顶级品种，产于广西梧州六堡镇。六堡镇有许多百年树龄的老茶树，这些老茶树的茶叶内含物质更加丰富，品质更加卓越。老茶树生长在亚热带高山地区，云雾缭绕，雨量充沛，茶叶叶片肥厚，持嫩度高。采摘百年老茶树的鲜叶制作六堡老茶，汤色红浓，陈香药香浓郁，滋味醇厚回甘，具有很高的保健价值和收藏价值。',
    teaEmoji: '🏝️',
    category: '广西黑茶',
    wuXing: '水',
    efficacyDetail: '梧州六堡老茶具有祛湿热、解毒消暑、消食化滞、降三高（高血压、高血脂、高血糖）、抗衰老的功效。百年老茶树的茶叶含有更加丰富的茶褐素、维生素和矿物质，对调节人体代谢、提高免疫力有显著效果。是养生保健的珍品。',
    altitude: '海拔300-800米',
    priceRange: 3,
    suitableTime: '午+晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 3,
    organic: false,
    award: '',
    rating: 5
  },
  {
    id: 193,
    name: '雅安康砖',
    type: '黑茶',
    origin: '四川雅安',
    grade: '一级',
    period: '唐代',
    desc: '康砖藏茶，保健佳品',
    detail: '雅安康砖产于四川雅安，是藏茶的传统品种之一。康砖选料考究，制作工艺传统，品质稳定可靠。',
    story: '暂无记载',
    efficacy: '助消化、补充维生素、降脂、利尿、解暑',
    gradeDesc: '一级：砖形完整，色泽褐红，汤色红浓，滋味醇和',
    color: '红浓明亮，滋味醇和',
    brewing: {temperature: '95-100℃', teaware: '煮茶壶', steps: '熬煮效果最佳，先洗茶后熬煮，可多次煮饮'},
    storage: '通风干燥保存，避免受潮，可长期保存',
    foodPairing: '酥油茶、糌粑、牛羊肉、奶酪、青稞面',
    tastingTerms: '康砖藏茶、汤色红浓、滋味醇和、解油腻',
    suitableCrowd: '藏族同胞、高原居民、以肉食为主者、户外工作者',
    flavorProfile: {bitter: 3, astringent: 4, sweet: 4, fragrant: 4, returning: 6},
    suitableSeason: '秋季、冬季',
    originDetail: '四川省雅安市雨城区、名山区，海拔500-1500米，川西高原过渡地带',
    storyExtended: '雅安康砖是藏茶的传统品种之一，产于四川省雅安市。康砖是历史上\"茶马互市\"的重要商品，主要销往藏区，是藏族同胞生活中不可或缺的饮料。雅安地区气候温和，茶叶品质优良，制成的康砖耐煮耐泡，非常适合高原地区的生活需求。康砖具有解油腻、助消化、补充维生素的功效，是高原居民的日常保健饮品。',
    teaEmoji: '🏔️',
    category: '边销黑茶',
    wuXing: '水',
    efficacyDetail: '雅安康砖具有助消化、补充维生素、降脂利尿、解暑清热的功效。藏茶中含有丰富的维生素C和维生素B族，可以补充高原饮食中蔬菜水果的不足。对促进消化、分解脂肪、维持身体健康有很好的效果。',
    altitude: '海拔500-1500米',
    priceRange: 1,
    suitableTime: '晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 2,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 4
  },
  {
    id: 194,
    name: '普洱紫芽',
    type: '黑茶',
    origin: '云南勐海',
    grade: '特级',
    period: '唐代',
    desc: '紫芽稀有，花青素高',
    detail: '普洱紫芽产于云南勐海，是采用紫芽茶树鲜叶制成的珍稀普洱茶。紫芽茶叶含有丰富的花青素，保健价值极高。',
    story: '暂无记载',
    efficacy: '抗氧化、延缓衰老、降血压、保护心血管、美容养颜',
    gradeDesc: '特级：芽叶呈紫红色，色泽紫褐，汤色金黄透亮，花青素香明显',
    color: '金黄透亮，紫芽独特',
    brewing: {temperature: '90-95℃', teaware: '紫砂壶或盖碗', steps: '洗茶后冲泡，第一泡5秒出汤，后续每泡延长，可冲泡15次以上'},
    storage: '通风干燥保存，避免潮湿，可长期保存越陈越香',
    foodPairing: '云南菜、粤菜、海鲜、滋补汤品',
    tastingTerms: '紫芽稀有、花青素高、汤色金黄、滋味醇厚、回甘持久',
    suitableCrowd: '女性、茶收藏家、三高患者、注重美容者、抗衰老需求者',
    flavorProfile: {bitter: 3, astringent: 4, sweet: 6, fragrant: 7, returning: 8},
    suitableSeason: '秋季、冬季、春季',
    originDetail: '云南省西双版纳傣族自治州勐海县，海拔1200-1800米，紫芽茶树林',
    storyExtended: '普洱紫芽是普洱茶中的珍稀品种，产于云南省勐海县。紫芽茶树是变异茶树品种，芽叶呈紫红色，这是因为茶叶中含有丰富的花青素。花青素是一种强抗氧化剂，对人体健康有诸多益处。紫芽茶树数量稀少，产量有限，因此极为珍贵。紫芽普洱茶汤色金黄透亮，口感醇厚，滋味独特，既有普洱茶的陈香，又有紫芽特有的花青素香气，是茶中珍品。',
    teaEmoji: '🍇',
    category: '云南普洱生茶',
    wuXing: '水',
    efficacyDetail: '普洱紫芽具有抗氧化、延缓衰老、降血压、保护心血管、美容养颜的功效。紫芽茶叶中花青素含量极高，是天然的抗氧化剂，对清除自由基、延缓细胞衰老、保护心脑血管健康有显著效果。经常饮用可改善皮肤状态，延缓衰老，是女性美容养颜的佳品。',
    altitude: '海拔1200-1800米',
    priceRange: 3,
    suitableTime: '午+晚',
    harvestSeason: '春',
    age: 0,
    caffeine: 3,
    processLevel: 2,
    organic: false,
    award: '',
    rating: 5
  }
]